databases:
  - name: ifrs9appdb
    plan: free
    databaseName: ifrs9app
    user: ifrs9app

services:
  - type: web
    plan: free
    name: ifrs9app
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ifrs9app.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifrs9appdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4