# Generated by Django 5.1.1 on 2025-02-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='company_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('report_date', models.DateField()),
                ('version', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Locked', 'Locked')], default='Active', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='impairment.company')),
                ('created_by', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_transition_matrix', models.JSONField(blank=True, null=True)),
                ('stage_1_cumulative', models.JSONField(blank=True, null=True)),
                ('stage_2_cumulative', models.JSONField(blank=True, null=True)),
                ('stage_1_marginal', models.JSONField(blank=True, null=True)),
                ('stage_2_marginal', models.JSONField(blank=True, null=True)),
                ('cures', models.JSONField(blank=True, null=True)),
                ('recoveries', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pd_calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomerLoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_data', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='ECLCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecl_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecl_calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='EADLGDCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=50, null=True)),
                ('stage', models.CharField(max_length=10, null=True)),
                ('loan_type', models.CharField(max_length=50, null=True)),
                ('effective_interest_rate', models.FloatField(max_length=15, null=True)),
                ('amortization_schedule', models.JSONField(blank=True, null=True)),
                ('lgd_schedule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ead_lgd_calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLoanBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_loan_data', to='impairment.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'report_date', 'version'), name='unique_version_per_company_and_date'),
        ),
        migrations.AddConstraint(
            model_name='eadlgdcalculationresult',
            constraint=models.UniqueConstraint(fields=('account_no', 'project'), name='unique_account_per_project'),
        ),
    ]
