# Generated by Django 5.1.1 on 2025-07-08 22:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment_engine_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gdp_coefficient',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.05'), max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='gdp_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='LGDRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='impairment_engine_v2.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LGDRiskFactorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_percentage', models.DecimalField(decimal_places=4, help_text='Loss Given Default percentage (e.g., 40.2345)', max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='impairment_engine_v2.lgdriskfactor')),
            ],
            options={
                'unique_together': {('factor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OLSCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tenor', models.BooleanField(default=False)),
                ('coefficient', models.DecimalField(decimal_places=6, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impairment_engine_v2.company')),
                ('factor_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impairment_engine_v2.lgdriskfactorvalue')),
            ],
            options={
                'unique_together': {('company', 'factor_value')},
            },
        ),
    ]
